### ISSUE TITLE
Support abstract classes that don't inherit from ::Class directly

### ISSUE THREAD

**Issue by snusnu** [dkubb/abstract_type#2]
This was previously needed in `dm-mapper`, but isn't anymore. Still, it may be a nice feature for `abstract_type`. The linked code didn't work for the general case, although that should be easy to implement.

https://github.com/datamapper/dm-mapper/commit/7f71b4c913cdab15de1beec83a4c3237df013653

Edit: from Object => from ::Class

**Comment by dkubb** [comment]
@snusnu I'm going to close this for now since I don't want to support abstract classes that are subclasses themselves. If it ever becomes an option I'll try to update this ticket with a reference.
