### ISSUE TITLE
ruby 1.8.7 compatibility

### ISSUE THREAD

**Issue by aq1018** [dkubb/abstract_type#8]
When running under ruby 1.8.7, I get the following error when trying to use `#abstract_singleton_method`:

```
NoMethodError: undefined method `define_singleton_method'
```

`Object#define_singleton_method` is only available in ruby 1.9+

**Comment by aq1018** [comment]
Maybe using the `backports` gem?

**Comment by mbj** [comment]
@aq1018 We do not officially support 1.8. You can require the backports gem before loading / using `abstract_type`.
